# Generated by Django 3.1.7 on 2021-03-23 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210323_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='technologies',
        ),
        migrations.AddField(
            model_name='language',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel', verbose_name=''),
        ),
        migrations.AddField(
            model_name='technology',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectmodel', verbose_name=''),
        ),
    ]
