# Generated by Django 3.1.7 on 2021-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210323_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='project',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='project',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='languages',
            field=models.ManyToManyField(to='projects.Language', verbose_name=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='technologies',
            field=models.ManyToManyField(to='projects.Technology', verbose_name=''),
        ),
    ]
