# Generated by Django 3.1.7 on 2021-03-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210323_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(max_length=265),
        ),
    ]
