# Generated by Django 3.1.7 on 2021-03-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210323_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='logo',
            field=models.ImageField(blank=True, upload_to='Language_Images'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(default='This is a short Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='Project_Images'),
        ),
        migrations.AddField(
            model_name='technology',
            name='logo',
            field=models.ImageField(blank=True, upload_to='Tech_Images'),
        ),
    ]
