# Generated by Django 3.1.7 on 2021-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210323_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='languages',
            field=models.ManyToManyField(related_name='languages', to='projects.Language'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(max_length=265, unique=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='technologies',
            field=models.ManyToManyField(related_name='technologies', to='projects.Technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
    ]
