# Generated by Django 3.1.7 on 2021-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210323_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='link_to_code',
            field=models.CharField(max_length=100, null=True, verbose_name='link To code'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='link_to_project',
            field=models.CharField(max_length=100, null=True, verbose_name='Link to project'),
        ),
    ]
